apiVersion: v1
kind: Service
metadata: 
  name: cpu-intensive-service
  namespace: tester
  labels:
    app: load-test
spec: 
  selector: 
    app: load-test
  ports:
    - name: web
      port: 80
      targetPort: 80
  #type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cpu-intensive-deployment
  namespace: tester
  labels:
    app: load-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-test
  template:
    metadata:
      labels:
        app: load-test
    spec:
      containers:
        - name: load-test-pod
          image: k8s.gcr.io/hpa-example
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 300m
              memory: 30Mi
            requests:
              cpu: 200m
              memory: 20Mi

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cpu-intensive-ing
  namespace: tester
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: loadtester.amit-eks-demo.amit.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cpu-intensive-service
          servicePort: 80
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-intensive-hpa
  namespace: tester
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-intensive-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
